name: Keep Alive Streamlit
on:
  schedule:
    - cron: '0 */1 * * *' # 每小時執行一次
  workflow_dispatch: # 支援手動觸發

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: curl -I https://winnerstock888-fbgrrwk5uur9hzvwezt6z3.streamlit.app/
